<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\mydb;

class DbSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        mydb::create([
            '_id'=>'admin',
            'MyLanguage'=>[
                'Menu'=>[
                    'SystemLang'=>'Edit my language',          
                    'Home'=>'Home',
                    'Branches'=>'Branches',
                    'ChangeLanguage'=>'Change language',
                    'CustomTable'=>'add and edit table',
                    'MyFlexTables'=>'flex table'
                ],
                'TableInfo'=>[
                    'MYTITLE'=>'table info',
                    'Ssearch'=>'Quick Search:',
                    'InfoEmpty'=>'No records available',
                    'ZeroRecords'=>'No Data Found',
                    'Info'=>'Total',
                    'LengthMenu'=>'records per page',
                    'InfoFiltered'=>'Showing'
                ],
                'Admin'=>[
                    'MYTITLE'=>'Admin',
                    'Title'=>'Admin user'
                ],
                'AppSettingAdmin'=>[
                    'MYTITLE'=>'App setting',
                    'Menu'=>'Menu',
                    'Offcanvas'=>'Dark offcanvas',
                    'Logout'=>'Logout',
                    'AdminDashboard'=>'Salamatak for medical analysis and radiology',
                    'BranchesCompany'=>'Select branches',
                    'BranchMain'=>'Branch main',
                    'AllNamesLanguage'=>'App lang',
                    'MyFlexTables'=>'My Flex Tables',
                    'InputNameTable'=>'Name',
                    'InputLabel'=>'Name',
                    'InputHint'=>'Enter name value',
                    'InputErrorsMessageReq'=>'error name reqired',
                    'InputErrorsMessageInv'=>'error name invalid',
                    'SelectBranchBox'=>'Select Branch Box',
                    'Html'=>'Html'
                ],
                'Register'=>[
                    'MYTITLE'=>'Register',
                    'Title'=>'Register page',
                    'Button'=>'Register',
                    'TitleForm'=>'Register admin',
                    'LabelEmail'=>'Email',
                    'HintEmail'=>'enter your email',
                    'RequiredEmail'=>'required email',
                    'InvalidEmail'=>'invalid email',
                    'LabelPassword'=>'Password',
                    'HintPassword'=>'enter your Password',
                    'RequiredPassword'=>'required Password',
                    'InvalidPassword'=>'Password less than 8 characters',
                    'DdIdReq'=>'required database id',
                    'DdIdInv'=>'invalid database id',
                    'SuccessfullyMessage'=>'successfully register admin',
                    'LoginRegisterMessage'=>'Successfully register admin',
                    'LabelPasswordConfirem'=>'Confirem password',
                    'HintPasswordConfirem'=>'Enter confirem password',
                    'Password_ConfiremInvalid'=>'password and confirem password dos not match',
                    'RequiredConforemPassword'=>'required Conforem Password',
                    'InvalidConforemPassword'=>'Conforem Password less than 8 characters',
                    'UserEmailExist'=>'This email already exists.',
                    'ButtonChangeLang'=>'Change my language',
                    'TitleChangeLang'=>'select your language',
                    'SaveChangeLang'=>'Save',
                    'ChangeLagUsed'=>'Language is used'
                ],
                'Login'=>[
                    'MYTITLE'=>'Login',
                    'Title'=>'Login page',
                    'Button'=>'Login',
                    'TitleForm'=>'Login admin',
                    'LabelEmail'=>'Email',
                    'HintEmail'=>'enter your email',
                    'RequiredEmail'=>'required email',
                    'InvalidEmail'=>'invalid email',
                    'LabelPassword'=>'Password',
                    'HintPassword'=>'enter your Password',
                    'RequiredPassword'=>'required Password',
                    'InvalidPassword'=>'Password less than 8 characters',
                    'DdIdReq'=>'required database id',
                    'DdIdInv'=>'invalid database id',
                    'EmailPassword'=>'error email and password',
                    'SuccessfullyMessage'=>'successfully loing admin',
                    'LoginRegisterMessage'=>'Successfully login admin',
                    'ButtonChangeLang'=>'Change my language',
                    'TitleChangeLang'=>'select your language',
                    'SaveChangeLang'=>'Save',
                    'ChangeLagUsed'=>'Language is used'
                ],
                'Html'=>[
                    'Direction'=>'ltr'
                ],
                'ChangeLanguage'=>[
                    'MYTITLE'=>'ChangeLanguage',
                    'IdIsReq'=>'Required id',
                    'IdIsInv'=>'invalid id',
                    'DbIdIsReq'=>'Required database id',
                    'DbIdIsInv'=>'invalid database id',
                    'ChangeLagUsed'=>'Language is used',
                    'SuccessMessage'=>'Successfully change language',
                    'Used'=>'language is used',
                    'LoadMessage'=>'welcome in Change Language',
                    'ButtonModelAdd'=>'Create language',
                    'ScreenModelCreate'=>'Screen create language',
                    'ButtonModelCreate'=>'Create language',
                    'MessageModelCreate'=>'Seccessfully create language',
                    'LabelCreateLanguage'=>'Name Langaue',
                    'ScreenModelDelete'=>'Screen delete language',
                    'MessageModelDelete'=>'do you want to delete language',
                    'ButtonModelDelete'=>'delete language',
                    'Title'=>'Change Language',
                    'NewLangNameRequired'=>'Required name',
                    'NewLangNameInvalid'=>'Inavalid name',
                    'NameLangaue'=>'Name',
                    'TableId'=>'Id',
                    'TabelEvent'=>'Event',
                    'LanguageInfo'=>'Hello, Welcome!',
                    'LanguageSelect'=>'Select a language to change the content:',
                    'LabelChangeLanguageMessage'=>'do you want to change language',
                    'LabelNewLangName'=>'Name',
                    'HintNewLangName'=>'Enter new lang name',
                    'ButtonChangeLanguageMessage'=>'Change language',
                    'ButtonModelEdit'=>'Edit language',
                    'TitleChangeLanguageMessage'=>'Screen change language',
                    'ScreenModelEdit'=>'Screen Edit language',
                    'UserIdIsReq'=>'Required user id',
                    'UserIdIsInv'=>'invalid user id',
                    'ChangeLang'=>'Seccessfully change language-',
                    'MessageModelEdit'=>'Seccessfully edit language',
                    'DeleteLanguage'=>'Seccessfully delete language-'
                ],
                'Branches'=>[
                    'MYTITLE'=>'branch',
                    'Used'=>'branch is used',
                    'LoadMessage'=>'welcome in branch main',
                    'Active'=>'this branch is used',
                    'BranceRaysNameRequired'=>'Name required',
                    'BranceRaysPhoneRequired'=>'Phone required',
                    'BranceRaysGovernmentsRequired'=>'Governments required',
                    'BranceRaysCityRequired'=>'City required',
                    'BranceRaysStreetRequired'=>'Street required',
                    'BranceRaysBuildingRequired'=>'Building required',
                    'BranceRaysAddressRequired'=>'Address required',
                    'BranceRaysCountryRequired'=>'Country required',
                    'BranceRaysFollowRequired'=>'Follow required',
                    'BranceRaysNameLength'=>'Name less than 3 characters',
                    'BranceRaysPhoneLength'=>'Invalid phone',
                    'BranceRaysGovernmentsLength'=>'Governments less than 3 characters',
                    'BranceRaysCityLength'=>'City less than 3 characters',
                    'BranceRaysStreetLength'=>'Street less than 3 characters',
                    'BranceRaysBuildingLength'=>'Building less than 3 characters',
                    'BranceRaysAddressLength'=>'Address less than 3 characters',
                    'BranceRaysCountryLength'=>'Country less than 3 characters',

                    'ScreenModelDelete'=>'Screen branch delete',
                    'MessageModelDelete'=>'Do you want to delete branch',
                    'ButtonModelDelete'=>'Delete',
                    'Title'=>'branches',
                    'ScreenModelCreate'=>'screen create branch',
                    'ScreenModelEdit'=>'edit branche screen',
                    'ButtonModelCreate'=>'Create new branche',
                    'ButtonModelAdd'=>'Add branch',
                    'ButtonModelEdit'=>'Edit branch',
                    'TableId'=>'Branch id',
                    'TabelEvent'=>'Event',

                    'BranchStreet'=>'Street',
                    'BranchName'=>'Name',
                    'BranchPhone'=>'Phone',
                    'BranchGovernments'=>'Governments',
                    'BranchCity'=>'City',
                    'BranchBuilding'=>'Building',
                    'BranchAddress'=>'Address',
                    'BranchCountry'=>'Country',
                    'BranchFollow'=>'Follow',
                    'BranchRaysName'=>'Enter branch name',
                    'BranchRaysPhone'=>'Enter branch phone',
                    'BranchRaysCountry'=>'Enter branch country',
                    'BranchRaysGovernments'=>'Enter branch governments',
                    'BranchRaysCity'=>'Enter branch city',
                    'BranchRaysStreet'=>'Enter branch street',
                    'BranchRaysBuilding'=>'Enter branch building',
                    'BranchRaysAddress'=>'Enter branch address',
                    'WithRaysOut'=>'Select in rays or out rays',
                    'MessageModelCreate'=>'Seccessfully branch add',
                    'BranceRaysFollowValue'=>'error in value',
                    'IdIsReq'=>'branch id required',
                    'IdIsInv'=>'branch id invalid',
                    'MessageModelEdit'=>'Seccessfully branch edit',
                    'BranchesChange'=>'Seccessfully change branch',
                    'Delete'=>'Seccessfully delete branch',
                ],
                'SelectBranchBox'=>[
                    'WithoutRays'=>'Without rays',
                    'WithRays'=>'With rays'
                ],
                'CustomTable'=>[
                    'MYTITLE'=>'custom table',
                    'LoadMessage'=>'welcome in page Custom Table',
                    'ScreenModelDelete'=>'Screen delete table',
                    'MessageModelDelete'=>'Do you want to delete table',
                    'ButtonModelDelete'=>'Delete table',
                    'Title'=>'Custom Table',
                    'ScreenModelCreate'=>'Screen create table',
                    'ScreenModelEdit'=>'Screen edit table',
                    'ButtonModelCreate'=>'Create table',
                    'ButtonModelAdd'=>'Create table',
                    'ButtonModelEdit'=>'Edit table',
                    'TableId'=>'Id',
                    'TabelEvent'=>'Event',
                    'MessageModelCreate'=>'Seccessfully add table',
                    'MessageModelEdit'=>'Seccessfully edit table',
                    'Delete'=>'Seccessfully delete table',
                    'IdIsReq'=>'Id Required',
                    'IdIsInv'=>'Id Invalid',
                    'NameTableIsReq'=>'name table Required',
                    'NameTableIsInv'=>'name table Invalid',
                    'NameTable'=>'Name',
                    'LabelName'=>'Name',
                    'HintName'=>'enter name table',
                    'InputNumberTableIsReq'=>'Input Numper table Required',
                    'InputNumberTableIsInv'=>'Input Numper table Invalid',
                    'LabelInputNumber'=>'Input Numper',
                    'HintInputNumber'=>'enter Input Numper table',
                ],
                'TablePage'=>[
                    'MYTITLE'=>'Table page',
                    'LoadMessage'=>'welcome in page table',
                    'ScreenModelDelete'=>'Screen delete table',
                    'MessageModelDelete'=>'Do you want to delete table',
                    'ButtonModelDelete'=>'Delete table',
                    'Title'=>'table',
                    'ScreenModelCreate'=>'Screen create table',
                    'ScreenModelEdit'=>'Screen edit table',
                    'ButtonModelCreate'=>'Create table',
                    'ButtonModelAdd'=>'Create table',
                    'ButtonModelEdit'=>'Edit table',
                    'TableId'=>'Id',
                    'TabelEvent'=>'Event',
                    'MessageModelCreate'=>'Seccessfully add table',
                    'MessageModelEdit'=>'Seccessfully edit table',
                    'Delete'=>'Seccessfully delete table',
                    'IdIsReq'=>'Id Required',
                    'IdIsInv'=>'Id Invalid',
                ],
                'SystemLang'=>[
                    'MYTITLE'=>'system language',
                    'TextRequired'=>'Text Required',
                    'TextLenght'=>'Invalid text',
                    'SystemLang'=>'System language',
                    'Text'=>'Text',
                    'WordHint'=>'Enter new value',
                    'DirectionPage'=>'Direction page',
                    'LanguageValue'=>'Value',
                    'LanguageName'=>'Name',
                    'Title'=>'Edit all words',
                    'TitleDirection'=>'Edit direction',
                    'SaveDirection'=>'Save direction',
                    'EditKeyInvalid'=>'Key Invalid',
                    'EditKey2Invalid'=>'Key2 Invalid',
                    'EditLanguageRequired'=>'Language required',
                    'EditTableRequired'=>'Table required',
                    'EditLanguageInvalid'=>'Language Invalid',
                    'EditTableInvalid'=>'Table Invalid',
                    'EditKeyRequired'=>'Key required',
                    'AllLanguageEdit'=>'Seccessfully edit language',
                    'ltr'=>'set left to right direction',
                    'rtl'=>'set right to left direction',
                    'TableId'=>'id',
                    'TabelEvent'=>'action',
                    'ButtonModelEdit'=>'save word',
                    'ScreenModelEdit'=>'screen edit word'
                ],
            ],
            'Setting'=>[
                'Language'=>'english'
            ],
            'Users'=>[
                'hgas5as'=>[
                    'Email'=>'ggamals7744@yahoo.com',
                    'Password'=>'ggamals7744@yahoo.com'
                ]
            ],
            'english'=>[
                'Menu'=>[
                    'SystemLang'=>'Edit my language',          
                    'Home'=>'Home',
                    'Branches'=>'Branches',
                    'ChangeLanguage'=>'Change language',
                    'CustomTable'=>'add and edit table',
                    'MyFlexTables'=>'flex table'
                ],
                'TableInfo'=>[
                    'MYTITLE'=>'table info',
                    'Ssearch'=>'Quick Search:',
                    'InfoEmpty'=>'No records available',
                    'ZeroRecords'=>'No Data Found',
                    'Info'=>'Total',
                    'LengthMenu'=>'records per page',
                    'InfoFiltered'=>'Showing'
                ],
                'AllNamesLanguage'=>[
                    'english'=>'English language',
                    // 'english2'=>'English language2',
                ],
                'Admin'=>[
                    'MYTITLE'=>'Admin',
                    'Title'=>'Admin user'
                ],
                'AppSettingAdmin'=>[
                    'MYTITLE'=>'App setting',
                    'Menu'=>'Menu',
                    'Offcanvas'=>'Dark offcanvas',
                    'Logout'=>'Logout',
                    'AdminDashboard'=>'Salamatak for medical analysis and radiology',
                    'BranchesCompany'=>'Select branches',
                    'BranchMain'=>'Branch main',
                    'AllNamesLanguage'=>'App lang',
                    'MyFlexTables'=>'My Flex Tables',
                    'InputNameTable'=>'Name',
                    'InputLabel'=>'Name',
                    'InputHint'=>'Enter name value',
                    'InputErrorsMessageReq'=>'error name reqired',
                    'InputErrorsMessageInv'=>'error name invalid',
                    'SelectBranchBox'=>'Select Branch Box',
                    'Html'=>'Html'
                ],
                'Register'=>[
                    'MYTITLE'=>'Register',
                    'Title'=>'Register page',
                    'Button'=>'Register',
                    'TitleForm'=>'Register admin',
                    'LabelEmail'=>'Email',
                    'HintEmail'=>'enter your email',
                    'RequiredEmail'=>'required email',
                    'InvalidEmail'=>'invalid email',
                    'LabelPassword'=>'Password',
                    'HintPassword'=>'enter your Password',
                    'RequiredPassword'=>'required Password',
                    'InvalidPassword'=>'Password less than 8 characters',
                    'DdIdReq'=>'required database id',
                    'DdIdInv'=>'invalid database id',
                    'SuccessfullyMessage'=>'successfully register admin',
                    'LoginRegisterMessage'=>'Successfully register admin',
                    'LabelPasswordConfirem'=>'Confirem password',
                    'HintPasswordConfirem'=>'Enter confirem password',
                    'Password_ConfiremInvalid'=>'password and confirem password dos not match',
                    'RequiredConforemPassword'=>'required Conforem Password',
                    'InvalidConforemPassword'=>'Conforem Password less than 8 characters',
                    'UserEmailExist'=>'This email already exists.',
                    'ButtonChangeLang'=>'Change my language',
                    'TitleChangeLang'=>'select your language',
                    'SaveChangeLang'=>'Save',
                    'ChangeLagUsed'=>'Language is used'
                ],
                'Login'=>[
                    'MYTITLE'=>'Login',
                    'Title'=>'Login page',
                    'Button'=>'Login',
                    'TitleForm'=>'Login admin',
                    'LabelEmail'=>'Email',
                    'HintEmail'=>'enter your email',
                    'RequiredEmail'=>'required email',
                    'InvalidEmail'=>'invalid email',
                    'LabelPassword'=>'Password',
                    'HintPassword'=>'enter your Password',
                    'RequiredPassword'=>'required Password',
                    'InvalidPassword'=>'Password less than 8 characters',
                    'DdIdReq'=>'required database id',
                    'DdIdInv'=>'invalid database id',
                    'EmailPassword'=>'error email and password',
                    'SuccessfullyMessage'=>'successfully loing admin',
                    'LoginRegisterMessage'=>'Successfully login admin',
                    'ButtonChangeLang'=>'Change my language',
                    'TitleChangeLang'=>'select your language',
                    'SaveChangeLang'=>'Save',
                    'ChangeLagUsed'=>'Language is used'
                ],
                'Html'=>[
                    'Direction'=>'ltr'
                ],
                'ChangeLanguage'=>[
                    'MYTITLE'=>'ChangeLanguage',
                    'IdIsReq'=>'Required id',
                    'IdIsInv'=>'invalid id',
                    'DbIdIsReq'=>'Required database id',
                    'DbIdIsInv'=>'invalid database id',
                    'ChangeLagUsed'=>'Language is used',
                    'SuccessMessage'=>'Successfully change language',
                    'Used'=>'language is used',
                    'LoadMessage'=>'welcome in Change Language',
                    'ButtonModelAdd'=>'Create language',
                    'ScreenModelCreate'=>'Screen create language',
                    'ButtonModelCreate'=>'Create language',
                    'MessageModelCreate'=>'Seccessfully create language',
                    'LabelCreateLanguage'=>'Name Langaue',
                    'ScreenModelDelete'=>'Screen delete language',
                    'MessageModelDelete'=>'do you want to delete language',
                    'ButtonModelDelete'=>'delete language',
                    'Title'=>'Change Language',
                    'NewLangNameRequired'=>'Required name',
                    'NewLangNameInvalid'=>'Inavalid name',
                    'NameLangaue'=>'Name',
                    'TableId'=>'Id',
                    'TabelEvent'=>'Event',
                    'LanguageInfo'=>'Hello, Welcome!',
                    'LanguageSelect'=>'Select a language to change the content:',
                    'LabelChangeLanguageMessage'=>'do you want to change language',
                    'LabelNewLangName'=>'Name',
                    'HintNewLangName'=>'Enter new lang name',
                    'ButtonChangeLanguageMessage'=>'Change language',
                    'ButtonModelEdit'=>'Edit language',
                    'TitleChangeLanguageMessage'=>'Screen change language',
                    'ScreenModelEdit'=>'Screen Edit language',
                    'UserIdIsReq'=>'Required user id',
                    'UserIdIsInv'=>'invalid user id',
                    'ChangeLang'=>'Seccessfully change language-',
                    'MessageModelEdit'=>'Seccessfully edit language',
                    'DeleteLanguage'=>'Seccessfully delete language-'
                ],
                'Branches'=>[
                    'MYTITLE'=>'branch',
                    'Used'=>'branch is used',
                    'LoadMessage'=>'welcome in branch main',
                    'Active'=>'this branch is used',
                    'BranceRaysNameRequired'=>'Name required',
                    'BranceRaysPhoneRequired'=>'Phone required',
                    'BranceRaysGovernmentsRequired'=>'Governments required',
                    'BranceRaysCityRequired'=>'City required',
                    'BranceRaysStreetRequired'=>'Street required',
                    'BranceRaysBuildingRequired'=>'Building required',
                    'BranceRaysAddressRequired'=>'Address required',
                    'BranceRaysCountryRequired'=>'Country required',
                    'BranceRaysFollowRequired'=>'Follow required',
                    'BranceRaysNameLength'=>'Name less than 3 characters',
                    'BranceRaysPhoneLength'=>'Invalid phone',
                    'BranceRaysGovernmentsLength'=>'Governments less than 3 characters',
                    'BranceRaysCityLength'=>'City less than 3 characters',
                    'BranceRaysStreetLength'=>'Street less than 3 characters',
                    'BranceRaysBuildingLength'=>'Building less than 3 characters',
                    'BranceRaysAddressLength'=>'Address less than 3 characters',
                    'BranceRaysCountryLength'=>'Country less than 3 characters',

                    'ScreenModelDelete'=>'Screen branch delete',
                    'MessageModelDelete'=>'Do you want to delete branch',
                    'ButtonModelDelete'=>'Delete',
                    'Title'=>'branches',
                    'ScreenModelCreate'=>'screen create branch',
                    'ScreenModelEdit'=>'edit branche screen',
                    'ButtonModelCreate'=>'Create new branche',
                    'ButtonModelAdd'=>'Add branch',
                    'ButtonModelEdit'=>'Edit branch',
                    'TableId'=>'Branch id',
                    'TabelEvent'=>'Event',

                    'BranchStreet'=>'Street',
                    'BranchName'=>'Name',
                    'BranchPhone'=>'Phone',
                    'BranchGovernments'=>'Governments',
                    'BranchCity'=>'City',
                    'BranchBuilding'=>'Building',
                    'BranchAddress'=>'Address',
                    'BranchCountry'=>'Country',
                    'BranchFollow'=>'Follow',
                    'BranchRaysName'=>'Enter branch name',
                    'BranchRaysPhone'=>'Enter branch phone',
                    'BranchRaysCountry'=>'Enter branch country',
                    'BranchRaysGovernments'=>'Enter branch governments',
                    'BranchRaysCity'=>'Enter branch city',
                    'BranchRaysStreet'=>'Enter branch street',
                    'BranchRaysBuilding'=>'Enter branch building',
                    'BranchRaysAddress'=>'Enter branch address',
                    'WithRaysOut'=>'Select in rays or out rays',
                    'MessageModelCreate'=>'Seccessfully branch add',
                    'BranceRaysFollowValue'=>'error in value',
                    'IdIsReq'=>'branch id required',
                    'IdIsInv'=>'branch id invalid',
                    'MessageModelEdit'=>'Seccessfully branch edit',
                    'BranchesChange'=>'Seccessfully change branch',
                    'Delete'=>'Seccessfully delete branch',
                ],
                'SelectBranchBox'=>[
                    'WithoutRays'=>'Without rays',
                    'WithRays'=>'With rays'
                ],
                'CustomTable'=>[
                    'MYTITLE'=>'custom table',
                    'LoadMessage'=>'welcome in page Custom Table',
                    'ScreenModelDelete'=>'Screen delete table',
                    'MessageModelDelete'=>'Do you want to delete table',
                    'ButtonModelDelete'=>'Delete table',
                    'Title'=>'Custom Table',
                    'ScreenModelCreate'=>'Screen create table',
                    'ScreenModelEdit'=>'Screen edit table',
                    'ButtonModelCreate'=>'Create table',
                    'ButtonModelAdd'=>'Create table',
                    'ButtonModelEdit'=>'Edit table',
                    'TableId'=>'Id',
                    'TabelEvent'=>'Event',
                    'MessageModelCreate'=>'Seccessfully add table',
                    'MessageModelEdit'=>'Seccessfully edit table',
                    'Delete'=>'Seccessfully delete table',
                    'IdIsReq'=>'Id Required',
                    'IdIsInv'=>'Id Invalid',
                    'NameTableIsReq'=>'name table Required',
                    'NameTableIsInv'=>'name table Invalid',
                    'NameTable'=>'Name',
                    'LabelName'=>'Name',
                    'HintName'=>'enter name table',
                    'InputNumberTableIsReq'=>'Input Numper table Required',
                    'InputNumberTableIsInv'=>'Input Numper table Invalid',
                    'LabelInputNumber'=>'Input Numper',
                    'HintInputNumber'=>'enter Input Numper table',
                ],
                'TablePage'=>[
                    'MYTITLE'=>'Table page',
                    'LoadMessage'=>'welcome in page table',
                    'ScreenModelDelete'=>'Screen delete table',
                    'MessageModelDelete'=>'Do you want to delete table',
                    'ButtonModelDelete'=>'Delete table',
                    'Title'=>'table',
                    'ScreenModelCreate'=>'Screen create table',
                    'ScreenModelEdit'=>'Screen edit table',
                    'ButtonModelCreate'=>'Create table',
                    'ButtonModelAdd'=>'Create table',
                    'ButtonModelEdit'=>'Edit table',
                    'TableId'=>'Id',
                    'TabelEvent'=>'Event',
                    'MessageModelCreate'=>'Seccessfully add table',
                    'MessageModelEdit'=>'Seccessfully edit table',
                    'Delete'=>'Seccessfully delete table',
                    'IdIsReq'=>'Id Required',
                    'IdIsInv'=>'Id Invalid',
                ],
                'SystemLang'=>[
                    'MYTITLE'=>'system language',
                    'TextRequired'=>'Text Required',
                    'TextLenght'=>'Invalid text',
                    'SystemLang'=>'System language',
                    'Text'=>'Text',
                    'WordHint'=>'Enter new value',
                    'DirectionPage'=>'Direction page',
                    'LanguageValue'=>'Value',
                    'LanguageName'=>'Name',
                    'Title'=>'Edit all words',
                    'TitleDirection'=>'Edit direction',
                    'SaveDirection'=>'Save direction',
                    'EditKeyInvalid'=>'Key Invalid',
                    'EditKey2Invalid'=>'Key2 Invalid',
                    'EditLanguageRequired'=>'Language required',
                    'EditTableRequired'=>'Table required',
                    'EditLanguageInvalid'=>'Language Invalid',
                    'EditTableInvalid'=>'Table Invalid',
                    'EditKeyRequired'=>'Key required',
                    'AllLanguageEdit'=>'Seccessfully edit language',
                    'ltr'=>'set left to right direction',
                    'rtl'=>'set right to left direction',
                    'TableId'=>'id',
                    'TabelEvent'=>'action',
                    'ButtonModelEdit'=>'save word',
                    'ScreenModelEdit'=>'screen edit word'
                ],
            ]
          
            
        ]); 
    }
}
